name: Update File
on:
    workflow_dispatch: 
    push:
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://download.8bitdo.cn/Manual/Mod-Kit/Mod-Kit-for-original-sega-saturn-controller.pdf
          dir: download