# This is a basic workflow to help you get started with Actions

name: ROG wol

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
     branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: ZeroTier
          uses: zerotier/github-action@v1.0.1
          with:
              network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
              auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
    
        - name: pinghost
          shell: bash
          run: |
            count=10
            while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
              echo "waiting..." ;
              sleep 1 ;
              let count=count-1
            done
            echo "ping success"

        - uses: actions/checkout@v3

        - name: python run
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - run: |
            pip install paramiko
            python wol.py ${{ secrets.OPENWRTB }} ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} ${{ secrets.ROG_WOL }}

        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 5
